Script started on Sun 09 Dec 2018 06:34:26 PM PST
]0;hiraj@laguna:hw5[hiraj@laguna hw5]$ make all
gcc -ansi -std=c99 -Wall -c MovieLab.c -o MovieLab.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c ImageList.c -lm -o ImageList.o
gcc -ansi -std=c99 -Wall -c IterativeFilter.c -o IterativeFilter.o
gcc -ansi -std=c99 -Wall -c Movie.c -o Movie.o
gcc -ansi -std=c99 -Wall -c MovieIO.c -o MovieIO.o
gcc -Wall MovieLab.o Image.o FileIO.o DIPs.o ImageList.o IterativeFilter.o Movie.o MovieIO.o -lm -o MovieLab
gcc -ansi -std=c99 -Wall -c -g -DDEBUG MovieLab.c -o MovieLab_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG Image.c -o Image_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG FileIO.c -o FileIO_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG DIPs.c -o DIPs_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG ImageList.c -lm -o ImageList_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG IterativeFilter.c -o IterativeFilter_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG Movie.c -o Movie_DEBUG.o
gcc -ansi -std=c99 -Wall -c -g -DDEBUG MovieIO.c -o MovieIO_DEBUG.o
gcc -Wall  MovieLab_DEBUG.o Image_DEBUG.o FileIO_DEBUG.o DIPs_DEBUG.o ImageList_DEBUG.o IterativeFilter_DEBUG.o Movie_DEBUG.o MovieIO_DEBUG.o -lm -o MovieLab_DEBUG
]0;hiraj@laguna:hw5[hiraj@laguna hw5]$ ./MovieLab -i HSSOE.ppm -o hue.yuv -start= 0 -end= 5  -step= 0.5 -hue
The movie file hue.yuv has been written successfully!
11 frames are written to the file hue.yuv in total.
]0;hiraj@laguna:hw5[hiraj@laguna hw5]$ ./MovieLab -m hue.yuv -o reverse.yuv -f 73 -s 300x20 0 -reverse
The movie file hue.yuv has been read successfully!
The movie file reverse.yuv has been written successfully!
73 frames are written to the file reverse.yuv in total.
]0;hiraj@laguna:hw5[hiraj@laguna hw5]$ make clean
rm *.o MovieLab MovieLab_DEBUG
]0;hiraj@laguna:hw5[hiraj@laguna hw5]$ exit
exit

Script done on Sun 09 Dec 2018 06:36:11 PM PST
