Script started on Mon 22 Oct 2018 10:46:03 AM PDT
]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ gcc PhotoLab.c -ansi - [K-std=c99 -Wall -o photo
]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ ./photo
---------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Sketch the edge of an image
5: Shuffle an image
6: Test all functions
7: Exit
please make your choice:	6
HSSOE.ppm was read.
Black and White modification applied
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
Edge Detection applied
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
Shuffle applied
shuffle.ppm was saved. 
shuffle.jpg was stored.


---------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Sketch the edge of an image
5: Shuffle an image
6: Test all functions
7: Exit
please make your choice:	7


]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ exit
exit

Script done on Mon 22 Oct 2018 10:46:41 AM PDT
