Script started on Sun 21 Oct 2018 02:44:35 PM PDT
]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ gcc P
PhotoLab.c    PhotoLab.txt  
]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ gcc PhotoLab.c a[K-ansi- [K -std=c99 -Wall -o photo
]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ ./photo
---------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Sketch the edge of an image
5: Shuffle an image
6: Test all functions
7: Exit
please make your choice:	6
HSSOE.ppm was read.
bw.ppm was saved. 
bw.jpg was stored.
HSSOE.ppm was read.
edge.ppm was saved. 
edge.jpg was stored.
HSSOE.ppm was read.
shuffle.ppm was saved. 
shuffle.jpg was stored.


---------------------------------------------
1: Load a PPM image
2: Save an image in PPM and JPEG format
3: Change a color image to Black & White
4: Sketch the edge of an image
5: Shuffle an image
6: Test all functions
7: Exit
please make your choice:	7


]0;hiraj@laguna:hw2[hiraj@laguna hw2]$ exit
exit

Script done on Sun 21 Oct 2018 02:45:46 PM PDT
